package com.dev.signatureonphoto.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig quoteDaoConfig;

    private final QuoteDao quoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        quoteDaoConfig = daoConfigMap.get(QuoteDao.class).clone();
        quoteDaoConfig.initIdentityScope(type);

        quoteDao = new QuoteDao(quoteDaoConfig, this);

        registerDao(Quote.class, quoteDao);
    }
    
    public void clear() {
        quoteDaoConfig.clearIdentityScope();
    }

    public QuoteDao getQuoteDao() {
        return quoteDao;
    }

}
